services:
  network-load-balancer-nginx:
    image: network-load-balancer-nginx
    build:
      context: ./nlb-nginx/
      dockerfile: Dockerfile
    init: true
    networks:
      - nlb
    restart: unless-stopped
    ports:
      - 8080:8080
  client-react-nginx-1:
    image: client-react-nginx
    build:
      context: ./client-react/
      dockerfile: DockerfileNlbAlb
    init: true
    networks:
      - nlb
      - alb-1
    restart: unless-stopped
  client-react-nginx-2:
    image: client-react-nginx
    build:
      context: ./client-react/
      dockerfile: DockerfileNlbAlb
    init: true
    networks:
      - nlb
      - alb-2
    restart: unless-stopped
  api-node-1-1:
    image: api-node
    build:
      context: ./api-node/
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - alb-1
      - db-1
    restart: unless-stopped
    hostname: api-node-1
  api-node-1-2:
    image: api-node
    build:
      context: ./api-node/
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - alb-1
      - db-1
    restart: unless-stopped
    hostname: api-node-2
  api-node-2-1:
    image: api-node
    build:
      context: ./api-node/
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - alb-2
      - db-2
    restart: unless-stopped
    hostname: api-node-1
  api-node-2-2:
    image: api-node
    build:
      context: ./api-node/
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - alb-2
      - db-2
    restart: unless-stopped
    hostname: api-node-2
  api-golang-1-1:
    image: api-golang
    build:
      context: ./api-golang/
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - alb-1
      - db-1
    restart: unless-stopped
    hostname: api-golang-1
  api-golang-1-2:
    image: api-golang
    build:
      context: ./api-golang/
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - alb-1
      - db-1
    restart: unless-stopped
    hostname: api-golang-2
  api-golang-2-1:
    image: api-golang
    build:
      context: ./api-golang/
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - alb-2
      - db-2
    restart: unless-stopped
    hostname: api-golang-1
  api-golang-2-2:
    image: api-golang
    build:
      context: ./api-golang/
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - alb-2
      - db-2
    restart: unless-stopped
    hostname: api-golang-2
  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks:
      - db-1
      - db-2
volumes:
  pgdata:
networks:
  nlb:
  alb-1:
  alb-2:
  db-1:
  db-2:
